### PR TITLE
🎉 Adding options to the initializer

### PR DESCRIPTION
**Pull request by mamadOuologuem**
I made this PR because I tried to add [custom dimension](https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets#send-custom-dimensions) at the initialization but I hadn't this options

### CODE REVIEW

**Comment by idmadj** [comment]
Hi there, is there anything wrong with calling `install` then `gtag` with the custom dimension, like this:
```js
install('GA_MEASUREMENT_ID');
gtag('config', 'GA_MEASUREMENT_ID', {
  'custom_map': {'dimension<Index>': 'dimension_name'}
});
```

**Comment by acdcjunior** [comment]
I believe the change proposed in this PR is necessary for us to use `{ send_page_view: false }`.

**Comment by mamadOuologuem** [comment]
@idmadj
Any second thought ?

**Comment by idmadj** [comment]
That's definitely a valid use case. Thanks @mamadOuologuem and @acdcjunior.

**Pull request merged**
